const $=id=>document.getElementById(id);let race=null,pos=null,map=null,userMarker=null,postLayer=null,currentPost=null;const RADIUS_DEFAULT=30;
const key=()=>race?'gpsRaceAnswers:'+race.name:'';function answers(){try{return JSON.parse(localStorage.getItem(key()))||{}}catch{return{}}}function saveAnswers(a){localStorage.setItem(key(),JSON.stringify(a));render()}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function dist(a,b,c,d){const R=6371000,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,A=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(A))}
$('chooseBtn').onclick=()=>$('raceFile').click();$('raceFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(x.format!=='gps-race-v1'||!Array.isArray(x.posts))throw 0;race=x;startRace()}catch{alert('Filen ser ikke ud til at være et GPS-løb fra opretter-appen.')}};r.readAsText(f)};
function startRace(){$('raceTitle').textContent=race.name;$('importCard').hidden=true;$('statusCard').hidden=false;$('mapCard').hidden=false;initMap();render();locate(true)}
function locate(watch=false){if(!navigator.geolocation){alert('Telefonen understøtter ikke GPS.');return}$('gpsBadge').textContent='Finder GPS…';const ok=p=>{pos={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};$('gpsBadge').textContent='GPS aktiv';$('gpsBadge').className='badge good';$('gpsStatus').textContent=`Præcision ±${Math.round(pos.accuracy)} m · Poster åbner inden for ${race.unlockRadius||RADIUS_DEFAULT} m.`;updateUser();render()};const bad=e=>{$('gpsBadge').textContent='GPS ikke tilladt';$('gpsBadge').className='badge bad';$('gpsStatus').textContent='Giv appen adgang til placering for at låse poster op.'};navigator.geolocation.getCurrentPosition(ok,bad,{enableHighAccuracy:true,timeout:15000,maximumAge:0});if(watch)navigator.geolocation.watchPosition(ok,()=>{}, {enableHighAccuracy:true,maximumAge:3000,timeout:20000})}
$('gpsBtn').onclick=()=>locate(false);function unlocked(p){return pos&&dist(pos.lat,pos.lng,p.lat,p.lng)<= (race.unlockRadius||RADIUS_DEFAULT)}
function render(){if(!race)return;const a=answers(),done=race.posts.filter(p=>a[p.id]).length;$('progress').textContent=`${done} / ${race.posts.length}`;$('progressFill').style.width=(race.posts.length?done/race.posts.length*100:0)+'%';$('posts').innerHTML=race.posts.map(p=>{const d=pos?Math.round(dist(pos.lat,pos.lng,p.lat,p.lng)):null,u=unlocked(p),ans=a[p.id];return `<article class="post ${u?'':'locked'} ${ans?'done':''}"><div class="postHead"><div class="postNo">${p.number}</div><div><h3>${u?esc(p.name):'🔒 Låst post'}</h3><p class="muted">${ans?'✓ Besvaret':u?'Posten er låst op':d===null?'Afventer GPS':`${d} m væk`}</p></div></div>${u?`<button data-open="${p.id}">${ans?'Se / ret svar':'Åbn post'}</button>`:''}</article>`}).join('');document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openPost(b.dataset.open));renderMarkers()}
function initMap(){if(!window.L)return;map=L.map('map').setView([56.2,10],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap-bidragydere'}).addTo(map);postLayer=L.layerGroup().addTo(map);setTimeout(()=>map.invalidateSize(),100)}
function renderMarkers(){if(!map||!race)return;postLayer.clearLayers();const bounds=[];race.posts.forEach(p=>{const u=unlocked(p),icon=L.divIcon({className:'numberMarker',html:`<span><b>${u?p.number:'🔒'}</b></span>`,iconSize:[34,34],iconAnchor:[17,34]});L.marker([p.lat,p.lng],{icon}).addTo(postLayer).bindPopup(u?esc(p.name):'Låst post');bounds.push([p.lat,p.lng])});if(!pos&&bounds.length)map.fitBounds(bounds,{padding:[30,30],maxZoom:16})}
function updateUser(){if(!map||!pos)return;const ll=[pos.lat,pos.lng];if(userMarker)userMarker.setLatLng(ll);else userMarker=L.circleMarker(ll,{radius:9,weight:3,fillOpacity:.8}).addTo(map).bindPopup('Dig');map.setView(ll,16);renderMarkers()}
function openPost(id){const p=race.posts.find(x=>x.id===id);if(!p||!unlocked(p))return;currentPost=p;const a=answers()[p.id]||{};$('postTitle').textContent=p.name;let body=p.type==='question'?`<p>${esc(p.question)}</p>`:`<p>${esc(p.description)}</p>${p.image?`<img class="postImage" src="${p.image}" alt="Billede til opgaven">`:''}`;$('postBody').innerHTML=body;if(p.type==='question'&&p.answerMode==='choices'){$('answerArea').innerHTML=(p.choices||[]).map((c,i)=>`<label class="choice"><input type="radio" name="choice" value="${i}" ${String(a.value)===String(i)?'checked':''}><span>${esc(c.text)}</span></label>`).join('')}else if(p.type==='question'){$('answerArea').innerHTML=`<label for="freeAnswer">Dit svar</label><input id="freeAnswer" class="textInput" value="${esc(a.value||'')}" placeholder="Skriv dit svar">`}else{$('answerArea').innerHTML=`<label for="taskPhoto">Billede som besvarelse (valgfrit)</label><input id="taskPhoto" type="file" accept="image/*" capture="environment">${a.image?`<img id="answerPreview" class="answerImage" src="${a.image}">`:'<img id="answerPreview" class="answerImage" hidden>'}<label for="taskNote">Kommentar (valgfrit)</label><textarea id="taskNote" rows="3">${esc(a.note||'')}</textarea>`;const inp=$('taskPhoto');inp.onchange=()=>compress(inp.files[0],data=>{const im=$('answerPreview');im.src=data;im.hidden=false;im.dataset.new=data})}$('postDialog').showModal()}
function compress(f,cb){if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1200,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);cb(c.toDataURL('image/jpeg',.75))};im.src=r.result};r.readAsDataURL(f)}
$('answerForm').onsubmit=e=>{e.preventDefault();if(!currentPost)return;const all=answers(),old=all[currentPost.id]||{},rec={time:new Date().toISOString()};if(currentPost.type==='question'&&currentPost.answerMode==='choices'){const v=document.querySelector('input[name=choice]:checked');if(!v){alert('Vælg et svar.');return}rec.value=Number(v.value);rec.correct=!!currentPost.choices[rec.value]?.correct}else if(currentPost.type==='question'){const v=$('freeAnswer').value.trim();if(!v){alert('Skriv et svar.');return}rec.value=v;rec.correct=String(v).trim().toLocaleLowerCase('da-DK')===String(currentPost.correctAnswer||'').trim().toLocaleLowerCase('da-DK')}else{const im=$('answerPreview');rec.image=im?.dataset.new||old.image||null;rec.note=$('taskNote').value.trim();rec.completed=true}all[currentPost.id]=rec;try{saveAnswers(all)}catch{alert('Billedet fylder for meget til telefonens lokale lager. Prøv et mindre billede.');return}$('postDialog').close()};$('closeDialog').onclick=$('cancelDialog').onclick=()=>$('postDialog').close();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
